### ISSUE TITLE
Getting "429 too many requests" error.

### ISSUE THREAD

**Issue by lss4** [furyutei/twMediaDownloader#10]
Recently when I'm downloading images it stops after a short while with this error (as short as only after about 30-40 tweets). When this 429 "Too many requests" error happens, I won't be able to get any new stuffs for the time being. However, I would be able to continue from the previously stopped position if I wait for an extended period.

It wasn't the case when I first used it, so I'm not sure about the exact reason why this is happening. Maybe [this](https://developer.twitter.com/en/docs/basics/rate-limiting) is related, but I don't think it's the same API used by other tools, as I could confirm this extension is able to download past the usual 3200 limit.

Is there a way to control the rate the extension gets media so that it wouldn't stop prematurely due to the error?

**Comment by furyutei** [comment]
I tried to improve it at [version 0.1.1.2401](https://github.com/furyutei/twMediaDownloader/tree/3cf95c60a38feef0f02f95a1e45942b7215accf7).
I changed the access method for acquiring information on videos.

**Note)**
User authorization of Twitter for this extenstion is required.
Since the approval popup is displayed at the initial download, please press the [Authorize app] button.
