### ISSUE TITLE
Medias not downloading anymore since 11 Aug 10pm UTC (Chrome and Firefox plugins)

### ISSUE THREAD

**Issue by liofeu** [furyutei/twMediaDownloader#43]
Hi

It was working very nicely untill at 11th August 20:00 UTC, but not working when I tried again at 22:00 UTC 11th August. 

The log message "[complete] - ( tweet: 0 / media: 0 )"  appears and no video/images are downloaded, for any twitter pages, any dates.

Same issue on Firefox and Chrome plugin.

Best,

**Comment by svetadoe** [comment]
I'm having the same issue, and it started at approximately the same time. I also tested both the Firefox and Chrome plugins, and neither is working. It seems like a few other people are reporting the same problem on the Chrome extension page. It seems to have something to do with a new Twitter update.

**Comment by doio** [comment]
Same here. Couldn't download any media since yesterday.

**Comment by ydoiliv20** [comment]
Same here. Is there an alternative tool that can save whole media at once?

**Comment by furyutei** [comment]
I'm aware of this defects.
Due to a revision on the Twitter side, the core part used in this extension is no longer available, so it no longer works.

Because of the need for drastic renovations, the timing of the renovations (including a survey to determine whether it is possible) has not yet been determined at this time (2020/08/13).
Thank you for your understanding.

**Comment by furyutei** [comment]
In [version 0.1.4.8](https://github.com/furyutei/twMediaDownloader/commit/919ed3355c6dc1e4450ba777c8446688bb49abd9), most of the existing features have been restored.

However, due to the limitations of Twitter's specifications (as far as I am currently aware), this may result in inefficient operation.
For example, if you specify a maximum date and time in the like timeline, there will be useless blank read before download starts.

**Comment by liofeu** [comment]
Thanks a lot
