### ISSUE TITLE
Firefox Extension hangs at Zipping on Firefox 105.0.1, and 106.0b3

### ISSUE THREAD

**Issue by doio** [furyutei/twMediaDownloader#87]
This is such a weird issue and I've only been experiencing it when the the browser updates to 105.0.1 (or when the extension updates to v0.1.4.31), didn't know why it was fine on 105.0 though. 

The main issue is that when you download a user's tweets and media, and when the created file size exceeds the limit, MediaDownloader will zip the files and when this happens, it takes a long time (longer than 30 minutes if the file created is 500MB), and it feels like it's taking forever to create the zip file. 

File creation is so slow even with file sizes like 2MB, or 4MB. 

I am using the latest v0.1.4.31 downloaded from https://addons.mozilla.org/ja/firefox/addon/tw-media-downloader/
Running Firefox 106.0b3.

I tried disabling the extension in Firefox and using the latest Tampermonkey script (also v0.1.4.31) instead and everything was working as it should have. No zipping issues whatsoever. 

I wonder if this is triggered by the newer versions of Firefox or the updated Extension. 

If I use the Tampermonkey alternative, Tweet ID Ranges are gone and I wouldn't know where to start, I wonder if the Tampermonkey script remembers such ranges at all.

**Comment by doio** [comment]
Update: 
It seems the Tampermonkey script of twMediaDownloader is also experiencing a decreased speed of zipping, but not as slow as the WebExtension one. Mmm

**Comment by doio** [comment]
Sorry I clicked the wrong button. I sincerely apologize. >_<

**Comment by fireattack** [comment]
I have been noticed this issue for a while, and I use Chrome.

It started about a few weeks ago I think.

**Comment by doio** [comment]
Glad I am not the only one having this kind of issue. Anyways, could this be related to JSZip?

**Comment by fireattack** [comment]
Ok, I think I know why. JSZip used to have a serious bug (https://github.com/Stuk/jszip/issues/617) that causes huge performance issue in 3.2.x. 

I knew this first hand because it affected one of my personal project as well.

twMediaDownloader used to use the known good version 3.1.5, until 6 months ago, where it was upgraded to the (still buggy) 3.9.1 (https://github.com/furyutei/twMediaDownloader/commit/af863947b44b1b3f4279fb983d16fd701a11f3db).

This bug was finally fixed in 3.10.x (https://github.com/Stuk/jszip/issues/617#issuecomment-1133329242) (took them 2+ years, but hey, it's fixed!).

@furyutei : please upgrade JSZip to 3.10.x+, or downgrade it back to 3.1.5. Thanks!

**Comment by doio** [comment]
@fireattack I came across that issue as well and tried the https://jsbin.com/kuxutodini/edit?html,console JSBIN thingy and replaced the 3.2.2 to the latest 3.10.1 and it seems it's even greater in performance. 

![20220926162213](https://user-images.githubusercontent.com/4461202/192228450-9db75471-1f8d-4687-8640-d585d44d6ee2.png)

**Comment by doio** [comment]
For Firefox, 0.1.4.32 fixed the issue and thank you guys!!! (*╹▽╹*)
